# Generates stub implementations for every Objective-C class declared in the
# macOS public headers, so the class list follows upstream automatically and
# any code that links MediaPipeTasksVision for x86_64 resolves. Classes whose
# API can report failure (`initWithOptions:error:`) return an NSError; plain
# `init` raises, because nothing in the stub can be used meaningfully.
#
# Usage: ruby generate-stub-classes.rb <headers-dir> <output.m>

headers_dir, output = ARGV
abort "Usage: #{$PROGRAM_NAME} <headers-dir> <output.m>" unless headers_dir && output

superclass_by_class = {}
Dir[File.join(headers_dir, '*.h')].sort.each do |header|
  File.read(header).scan(/^@interface ([A-Za-z0-9_]+) *: *([A-Za-z0-9_]+)/) do |name, superclass|
    superclass_by_class[name] = superclass
  end
end
abort "No Objective-C classes found in #{headers_dir}" if superclass_by_class.empty?

# Emit superclasses before their subclasses.
ordered = []
emitted = ['NSObject']
remaining = superclass_by_class.dup
until remaining.empty?
  ready = remaining.select { |_, superclass| emitted.include?(superclass) }.keys.sort
  abort "Classes with unresolved superclasses: #{remaining.keys.join(', ')}" if ready.empty?
  ordered.concat(ready)
  emitted.concat(ready)
  ready.each { |name| remaining.delete(name) }
end

stubs = ordered.map do |name|
  <<~OBJC
    @interface #{name} : #{superclass_by_class[name]}
    @end

    @implementation #{name}
    - (instancetype)init {
        MPPStubRaise(@"#{name}");
    }
    - (nullable instancetype)initWithOptions:(id)options error:(NSError **)error {
        if (error) {
            *error = MPPStubError(@"#{name}");
        }
        return nil;
    }
    @end
  OBJC
end

File.write(output, <<~OBJC)
  // Generated by scripts/build-x86_64-stub.sh from macos/Headers. Do not edit.

  #import "MPPStub.h"

  #{stubs.join("\n")}
OBJC
