name: Build
on: [push, pull_request]
env:
  DEVELOPER_DIR: "/Applications/Xcode_26.6.app/Contents/Developer"
jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - run: make all
