name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      - run: make all
